# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to "
#              "eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.",
#      "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = [
                     {'type': "boolean", 'difficulty': "easy", 'category': "General Knowledge",
                      'question': "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                      'correct_answer': "True", 'incorrect_answers': ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Nutella is produced by the German company Ferrero.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "When you cry in space, your tears stick to your face.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                      "question": "Scotland voted to become an independent country during the referendum from "
                                  "September 2014.",
                      "correct_answer": "False", "incorrect_answers": ["True"]}]
